version: '3.8'

services:
  comfyui:
    build: .
    ports:
      - "8189:8188"
    volumes:
      - ./ComfyUI:/workspace/ComfyUI
      - comfyui_venv:/opt/venv
      - pip_cache:/root/.cache/pip
    environment:
      - NVIDIA_VISIBLE_DEVICES=ALL
      - PATH=/opt/venv/bin:$PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  comfyui_venv:
  pip_cache:
