version: '3.8'

services:
  comfyui:
    build: 
      context: .
      args:
        COMFYUI_VERSION: v0.3.59
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/ComfyUI/models
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
